#!/bin/bash

# Logs
# tail -f /tmp/yabai_$USER.err.log
# tail -f /tmp/yabai_$USER.out.log

# Set up scripting addition with visudo
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai

# or manally pase into
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai)"
# sudo visudo -f /private/etc/sudoers.d/yabai

# Source which machine you're running
source "$HOME/.config/machine.sh"
source "$HOME/.config/yabai/_displays.sh"

# Set up Home Configuration
home=$(
  yabai -m config \
    external_bar all:44:0 \
    mouse_follows_focus off \
    focus_follows_mouse autoraise \
    window_origin_display focused \
    window_placement second_child \
    window_zoom_persist on \
    window_shadow on \
    window_animation_easing ease_out_circ \
    window_opacity_duration 0.1 \
    active_window_opacity 0.97 \
    normal_window_opacity 0.65 \
    window_opacity on \
    insert_feedback_color 0xCD0000FF \
    split_ratio 0.50 \
    split_type auto \
    auto_balance off \
    top_padding 22 \
    bottom_padding 33 \
    left_padding 33 \
    right_padding 33 \
    window_gap 33 \
    mouse_modifier ctrl \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action stack
)
# Old, drag to split window action
# mouse_drop_action swap

# window_animation_duration 0.00 \ commented for office SIP

# Deprecated configuration commands
# window_animation_frame_rate 120 \

# Set up Office Configuration
office=$home

# Load Yabai
if [[ "$MACHINE" == 'home' ]]; then

  yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
  sudo yabai --load-sa

  # load config
  $home
else

  printf "\033[0;32mSkipping yabai scripting addition for work.\033[0m\n\n" # global settings
  yabai -m signal --add event=dock_did_restart action="sudo yabai"
  yabai

  # load office-adjusted config
  $office

fi

# set up spaces after applying all configuration
source $HOME/.config/yabai/_spaces.sh

# add signals and manage applications
source $HOME/.config/yabai/_signals.sh
source $HOME/.config/yabai/_app-management.sh

# Apply the various rules that have been queued up
yabai -m rule --apply

printf "\033[0;32m✓ Yabai configuration loaded!\033[0m\n\n"
